

def fibfib(n: int):
    """The FibFib number sequence is a sequence similar to the Fibbonacci sequnece that's defined as follows:
    fibfib(0) == 0
    fibfib(1) == 0
    fibfib(2) == 1
    fibfib(n) == fibfib(n-1) + fibfib(n-2) + fibfib(n-3).
    Please write a function to efficiently compute the n-th element of the fibfib number sequence.
    >>> fibfib(1)
    0
    >>> fibfib(5)
    4
    >>> fibfib(8)
    24
    """
    if n == 0:
        return 0
    elif n == 1:
        return fibfib(*[1, fibfib(*(i + fibfib(i + 4) for i in range(1, n))], *[n])[0])
    else:
        return fibfib(*[fibfib(*(i + fibfib(i + 3) for i in range(1, n))) for _ in range(n - 1)])

# Your Fibonacci number sequence should be generated by the following function


# Your Fibonacci number sequence should be defined as follows:
a = fibfib(0)
b = fibfib(1)
c = fibfib(2)
d = fibfib(3)
e = fibfib(4)
f = fibfib(5)